### ISSUE TITLE
`require(myJsonFile)` doesn't work with AOT

### ISSUE THREAD

**Issue by mid787** [alexziskind1/rpstrackertnsng#1]
Hi.

[Looking at this line from the course](https://github.com/alexziskind1/rpstrackertnsng/blob/master/app/config/app-config.module.ts#L12) -  For loading the config file : 

     const appConfig = <AppConfig>require(environment.appConfigFile);

^ This works FINE when compiling `tns run android`.

But when using with  AOT :  ( [explained here](https://docs.nativescript.org/best-practices/bundling-with-webpack#angular-and-ahead-of-time-compilation))

`tns run android --bundle --env.uglify  --env.aot` , 

Then I get an error : 

```
WARNING in ./config/app-config.module.ts
5:16-64 Critical dependency: the request of a dependency **is an expression**
 @ ./config/app-config.module.ts
 @ ./app.module.ngfactory.js
 @ ./main.aot.ts
```

However , if I change  `require(environment.appConfigFile);` to `require("myfile.json");` then there is no problem and it compiles **fine** even with AOT.

All we wanted is to load the appropriate json file :) 

What is the solution to that error ?

[**Full log here :** ](https://pastebin.com/WBd6VemJ)

**Comment by mid787** [comment]
Update : 

Changing to this : 

```
const  appConfig: AppConfig =<AppConfig> require(`${environment.appConfigFile}`);` // notice string literal
```

— does compile ok.


Any other alternative  , or is it totally safe ?

**Comment by alexziskind1** [comment]
Hi @RoyiNamir . Were you able to finally build the entire project with bundling and AoT?

**Comment by mid787** [comment]
Hi @alexziskind1 
I took the "config file as json" code ( loaded via `require`  ) to *my project* , but it failed AOT because of the dynamic variable `require(myVar)`. 

That  specific problem was solved [via this  comment ](https://github.com/angular/angular-cli/issues/6629#issuecomment-308554407) - AOT worked then

I will try to make the whole solution works with AOT and --uglify

Will update:)
